import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/Providers";
import { TopNav } from "@/components/navbar/TopNav";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NextMatch",
  description:
    "Generated by create next app; this appears under the site name in Google when searched, and in social share",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <TopNav />
          {/* Note: I'm using vertical-center custom class here, he used it in the LoginPage component */}
          {/* I think it's a good solution provided that we use our own scrollbar in pages */}
          <main className="container mx-auto vertical-center">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
